### ISSUE TITLE
README a little unclear

### ISSUE THREAD

**Issue by Blinky-Keys** [RigidSeine/chat-less#1]
# Problem Description

The `README.md` file doesn't completely explain the entire setup process. I've opened a pull request to add in some information that would benefit users installing this project on a Linux system based on personal experience of trying to install the project myself. I've not linked the PR to this issue since it doesn't completely address all of the points raised here. 

# Other things to address

Listed here are some other things that don't appear to be fully covered in the `README`:

1. Where is the `.env` file supposed to go? Based on the flow of the `README`, it appears that this file needs to be placed in the `server` directory, but this isn't completely clear. This may be related to another issue where messages aren't saved to the database (regardless of whether the database is local or remote). 
2. If the database is being run locally (and not on Atlas), what is supposed to happen with the cluster URL? The inclusion of this variable is hardcoded in the `uri` in `server/services/mongodb-create-ypl-client.jsx`, making it appear that the application is unable to accommodate a locally hosted DB that doesn't have a cluster URL:

```js
const uri = `mongodb+srv://${dbUsername}:${dbPassword}@${clusterUrl}/?authMechanism=${authMechanism}`;
```
3. For a locally hosted DB, does a new user account need to be created first?

**Comment by RigidSeine** [comment]
1. If based on the flow of the readme that the file needs to be placed in the server directory then that's how it should be. 
2. Local database not supported.
3. See above.

**Comment by Blinky-Keys** [comment]
If hosting the database locally isn't supported then you'll want to review the content of the `README` again. The PR (#2) added instructions for hosting the DB locally which have been merged, making the `README` inaccurate. 

I would also definitely recommend being explicit about where the `.env` file should be located to reduce ambiguity and ensure that the setup process is as easy as possible.
